### PR TITLE
Fixing MQTT client

### PR DESCRIPTION
**Pull request by st3veV**
Adding mandatory endianness to to_bytes in MQTT client.

### CODE REVIEW

**Comment by st3veV** [comment]
Issue also mentioned in forum (https://forum.pycom.io/topic/2092/simple-mqtt-client-not-working)

**Comment by danicampora** [comment]
Thanks! fixed here: https://github.com/pycom/pycom-libraries/commit/ed5a5cf03128813bbcdee2af455c4f75adbfaa4f

**Comment by st3veV** [comment]
no problem
I'm wondering just wondering, what was wrong with this PR that made it not mergeable? I'd like to avoid it next time to be able to get "meaningless internet karma points" in form of contribution. ;)

**Comment by danicampora** [comment]
@st3veV sorry about that. I'm in China with poor internet connectivity and for me it was a lot easier to merge it like that. I did add your github name to the PR message.

**Pull request closed without merging**
