### PR TITLE
add HMC5883L driver for 3-Axis Digital Compass IC

### PR DESCRIPTION
**Pull request by livius2**
First version of driver
without compensate, selftest and calibration but good point to start.
Slightly optimized form memory allocation in every m.readAxes()

### CODE REVIEW

**Comment by Bucknalla** [comment]
Looks good! 👍 I'll give this a test when I get back to the office and take a look at the merge conflicts!

**Comment by livius2** [comment]
You can write somwhere that this is e.g. in popular GY-271 because not all know what is HMC5883L ;-)

**Comment by Bucknalla** [comment]
Hi @livius2 I've ordered a HMC5883L to test this out! Should arrive Monday - I'll give your code a test and then get it committed into the repo.

**Comment by Bucknalla** [comment]
Hi @livius2, I'm having trouble getting your lib to run on my GY-271. I'll give it another try on Monday but in the meantime, can you please create a new pull request for just the HMC5883L lib and test script?

Thanks!

Alex

**Comment by livius2** [comment]
@Alex i do not know how i ommit this message from you
I found it now in my spam e-mail folder

May knowledge about git is strongly limited i do not know how to do separete pull request.
Please contact me directly throught forum chat or by e-mail.
PS. for me it work

regards, 
Karol

**Comment by Bucknalla** [comment]
@livius2 No worries! :) I'm happy to help you!

I would suggest creating a pull request from your fork from commits:
Create HMC5883L.py - 3283064b05b262e39a62098f8ca08c5f519100ae
Create testCompass.py - 65537c9724f14a0d92155f4c0bbe09bebf66d2f3

This way you're only pushing what you have been working on. I've linked to the git documentation so you can see how to make a pull request with start and end commits!

https://git-scm.com/docs/git-request-pull

Thanks!

**Comment by livius2** [comment]
I will look into git docs and back to you.
But may i ask what problem do you have with GY-271?

**Comment by livius2** [comment]
```
S:\GITHUB\pycom-libraries [livius2-HMC5883L ?]> git request-pull -p 3283064b05b2
62e39a62098f8ca08c5f519100ae https://github.com/pycom/pycom-libraries.git 65537c
9724f14a0d92155f4c0bbe09bebf66d2f3
warn: No match for commit 65537c9724f14a0d92155f4c0bbe09bebf66d2f3 found at http
s://github.com/pycom/pycom-libraries.git
warn: Are you sure you pushed '65537c9724f14a0d92155f4c0bbe09bebf66d2f3' there?
The following changes since commit 3283064b05b262e39a62098f8ca08c5f519100ae:
```
Hi, i tried without any success. More hints about?

**Comment by livius2** [comment]
done this differently
I have created new branch from pycom/master
then i have cherry-pick "this two commits"
push
and then i have  created separate pull request #8

**Comment by livius2** [comment]
I have added also separate pull for onewire #9
now this #6 can be closed as replaced by #8 and #9

**Pull request closed without merging**
